spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test?serverTimezone=UTC
    username: root
    password: 1123

  main:
    banner-mode: off